/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onezao_onezao_pressurediagram0130_PressureDiagramActivity */

#ifndef _Included_com_onezao_onezao_pressurediagram0130_PressureDiagramActivity
#define _Included_com_onezao_onezao_pressurediagram0130_PressureDiagramActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onezao_onezao_pressurediagram0130_PressureDiagramActivity
 * Method:    startMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onezao_onezao_pressurediagram0130_PressureDiagramActivity_startMonitor
  (JNIEnv *, jobject);

/*
 * Class:     com_onezao_onezao_pressurediagram0130_PressureDiagramActivity
 * Method:    stopMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_onezao_onezao_pressurediagram0130_PressureDiagramActivity_stopMonitor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
